In [1]:
import numpy as np

np_array1 = np.ones([5] * 2)
np_array2 = np.array([[5, 5, 5, 5, 5]] * 5)
np_array3 = np.array([[6, 1, 1, 1, 6],
                      [1, 6, 1, 6, 1],
                      [1, 1, 6, 1, 1],
                      [1, 6, 1, 6, 1],
                      [6, 1, 1, 1, 6]])


result1 = np_array1 + np_array2
result2 = result1 * np_array3

print(result1)
print(result2)


[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]
